name: mike_test_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to pub.dev using `flutter pub publish`.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0
  firebase_storage: ^12.3.1
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  auto_size_text: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  ini: ^2.1.0
  connectivity_plus: ^6.1.0
  #url_launcher: ^6.0.20
  url_launcher: ^6.3.1
  #flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/nemsuniteicon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/nemsuniteicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # optionally, as transparency is not allowed on app store
  # web:
  #   generate: true
  #   image_path: "assets/icons/nemsuniteicon.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"

  # windows:
  #   generate: true
  #   image_path: "assets/icons/nemsuniteicon.png"
  #   icon_size: 48 # min:48, max:256, default: 48

  # macos:
  #   generate: true
  #   image_path: "assets/icons/nemsuniteicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/